[project]
name = "kota-wm"
version = "0.1.0"
description = "WM+RL project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.2",
    "modal>=1.5.5",
    "networkx[default]>=3.7",
    "numpy>=2.5.3",
    "onnx>=1.23.0",
    "onnxruntime>=1.30.0",
    "termcolor>=3.3.0",
    "torch==2.14.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
